-- ============================================================================
-- OS-103 · Cancelar o ingresso e pedir reembolso pela conta do comprador
--
-- Por que (01/10/2026): o comprador só conseguia pedir reembolso por e-mail ou
-- WhatsApp. Alguém da casa conferia na mão, o João pagava o PIX e depois o
-- pedido era cancelado no sistema. O Decreto 7.962 (art. 5º) pede que a
-- desistência seja feita pela mesma ferramenta da compra, com confirmação na
-- hora. E o caso da Luana (01/10) mostrou o risco de dinheiro: o pedido de
-- repasse dela incluía R$ 100 de um ingresso que estava sendo reembolsado.
--
-- Decisões do Gabriel (caixinha, 02/10/2026):
--   1. A CASA APROVA ANTES. O clique do comprador gera um pedido; o ingresso
--      fica BLOQUEADO (não entra, não transfere) até alguém aprovar. Só a
--      aprovação cancela o ingresso e devolve a vaga.
--   2. PIX pela fila; compra no cartão volta no cartão. NADA É PAGO PELO
--      SISTEMA: a fila mostra o que pagar, a casa paga e dá baixa.
--   3. INGRESSO POR INGRESSO. O comprador escolhe quais devolver.
--   4. A taxa dentro dos 7 dias espera o advogado: a regra mora em UMA função
--      (`reembolso_regra`) e muda em uma linha.
--
-- O que este arquivo faz, na ordem:
--   1. tabelas `reembolsos` e `reembolso_ingressos` (o pedido e seus ingressos)
--   2. a regra (prazo e taxa) e o valor de cada ingresso, cada um em um lugar só
--   3. as portas do comprador: simular, pedir, desistir
--   4. a trava: ingresso com reembolso em análise não entra nem é transferido
--   5. as portas da casa: listar, aprovar, recusar, dar baixa
--   6. a conta do repasse: reembolso (pendente ou feito) sai do valor do produtor
--   7. o aviso para a casa (mesmo motor do aviso de repasse)
--
-- PEDIDO NUNCA É APAGADO. Aprovar reaproveita `cancel_paid_order` quando o
-- pedido fica sem ingresso válido; quando sobra ingresso, o pedido continua
-- `paid` e só os ingressos devolvidos viram `cancelled`.
-- ============================================================================

-- ── 1. O pedido de reembolso ────────────────────────────────────────────────
create table if not exists public.reembolsos (
  id                uuid primary key default gen_random_uuid(),
  -- O protocolo que o comprador vê e a casa cita no WhatsApp.
  numero            bigint generated by default as identity (start with 1001) unique,
  order_id          uuid not null references public.orders(id),
  event_id          uuid not null references public.events(id),
  -- Quem pediu. Sem FK de propósito: a conta pode ser excluída (LGPD) e o
  -- registro do dinheiro devolvido tem que ficar.
  user_id           uuid not null,
  -- solicitado → a casa ainda não olhou; os ingressos estão bloqueados
  -- aprovado   → ingressos cancelados, vaga devolvida; falta pagar
  -- pago       → a casa deu baixa
  -- recusado   → a casa negou; os ingressos voltam a valer
  -- desistido  → o comprador voltou atrás antes da resposta
  status            text not null default 'solicitado'
                    check (status in ('solicitado','aprovado','pago','recusado','desistido')),
  -- Valores CONGELADOS no momento do pedido: é a regra daquele dia que vale,
  -- mesmo que a regra mude depois.
  valor_ingressos   numeric(12,2) not null check (valor_ingressos >= 0),
  valor_taxa        numeric(12,2) not null default 0 check (valor_taxa >= 0),
  devolve_taxa      boolean not null default false,
  valor_a_devolver  numeric(12,2) not null check (valor_a_devolver >= 0),
  -- O que a regra respondeu: janela, versão da Política aceita, prazos.
  regra             jsonb not null default '{}'::jsonb,
  -- 'pix' = a casa paga na chave informada · 'cartao' = estorno no cartão
  forma             text not null check (forma in ('pix','cartao')),
  chave_pix         text,
  tipo_chave_pix    text check (tipo_chave_pix is null or tipo_chave_pix in ('cpf','cnpj','email','telefone','aleatoria')),
  motivo            text,
  solicitado_em     timestamptz not null default now(),
  decidido_em       timestamptz,
  decidido_por      uuid,
  motivo_recusa     text,
  -- Como o cancelamento foi feito na aprovação: 'pedido_inteiro' | 'parcial' | 'pedido_ja_encerrado'
  modo_cancelamento text,
  pago_em           timestamptz,
  pago_por          uuid,
  observacao_pagamento text,
  comprovante_path  text,
  desistido_em      timestamptz,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  constraint reembolsos_pix_tem_chave check (forma <> 'pix' or chave_pix is not null)
);

comment on table public.reembolsos is
  'Pedido de reembolso feito pelo comprador em Meus Ingressos. A casa aprova, paga por fora e dá baixa. O sistema nunca movimenta dinheiro.';

-- Um pedido em análise por compra, de cada vez (mesma ideia do
-- `uniq_payout_requested_per_event`): evita clique duplo e fila duplicada.
create unique index if not exists uq_reembolso_solicitado_por_pedido
  on public.reembolsos (order_id) where status = 'solicitado';
create index if not exists idx_reembolsos_order  on public.reembolsos (order_id);
create index if not exists idx_reembolsos_user   on public.reembolsos (user_id);
create index if not exists idx_reembolsos_status on public.reembolsos (status, solicitado_em);

create table if not exists public.reembolso_ingressos (
  reembolso_id   uuid not null references public.reembolsos(id) on delete cascade,
  ticket_id      uuid not null references public.tickets(id),
  valor_ingresso numeric(12,2) not null default 0,
  valor_taxa     numeric(12,2) not null default 0,
  primary key (reembolso_id, ticket_id)
);

comment on table public.reembolso_ingressos is
  'Quais ingressos entram em cada pedido de reembolso, com o valor de cada um congelado.';

create index if not exists idx_reembolso_ingressos_ticket on public.reembolso_ingressos (ticket_id);

alter table public.reembolsos enable row level security;
alter table public.reembolso_ingressos enable row level security;

-- O comprador vê os próprios pedidos; quem administra vê todos. Ninguém
-- escreve pela chave pública: tudo passa pelas funções abaixo.
drop policy if exists "comprador ve seus reembolsos" on public.reembolsos;
create policy "comprador ve seus reembolsos"
  on public.reembolsos for select
  using (user_id = auth.uid() or public.has_role(auth.uid(), 'admin'::app_role));

drop policy if exists "comprador ve os ingressos dos seus reembolsos" on public.reembolso_ingressos;
create policy "comprador ve os ingressos dos seus reembolsos"
  on public.reembolso_ingressos for select
  using (exists (
    select 1 from public.reembolsos r
     where r.id = reembolso_id
       and (r.user_id = auth.uid() or public.has_role(auth.uid(), 'admin'::app_role))
  ));

revoke all on public.reembolsos from anon, authenticated;
revoke all on public.reembolso_ingressos from anon, authenticated;
grant select on public.reembolsos to authenticated;
grant select on public.reembolso_ingressos to authenticated;

drop trigger if exists update_reembolsos_updated_at on public.reembolsos;
create trigger update_reembolsos_updated_at
  before update on public.reembolsos
  for each row execute function public.update_updated_at_column();

-- ── 2a. A REGRA, em um lugar só ─────────────────────────────────────────────
-- Espelha as seções 2, 3 e 7 da Política de Reembolso (e o `RESUMO_REEMBOLSO`
-- do site). Mudou a Política, muda AQUI, e em nenhum outro lugar: a tela do
-- comprador e a fila da casa só mostram o que esta função responde.
--
--   · arrependimento: até 7 dias corridos da compra, faltando mais de 7 dias
--     para o evento;
--   · fora disso: até 48 horas antes do início do evento;
--   · taxa de serviço: NÃO volta na desistência do comprador (regra de 30/09).
--     Exceção: quem comprou aceitando o texto ANTIGO da Política (versão
--     anterior a 2026-09-30), que prometia "integral, incluindo taxas" no
--     arrependimento. Para essas compras a taxa volta dentro dos 7 dias.
--
-- ⏳ ITEM 4 DA OS-103 (espera o advogado): se a resposta for "a taxa volta nos
-- 7 dias para todo mundo", a mudança é a linha marcada com [TAXA] abaixo.
create or replace function public.reembolso_regra(_order_id uuid, _agora timestamptz default now())
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $regra$
declare
  _o       record;
  _e       record;
  _forma   text;
  _inicio  timestamptz;
  _limite  timestamptz;
  _fim_arrependimento timestamptz;
  _janela  text;
  _versao  text;
  _texto_antigo boolean;
  _devolve_taxa boolean;
begin
  select o.id, o.status, o.sale_origin, o.payment_method, o.total_amount, o.created_at, o.event_id, o.user_id
    into _o
    from public.orders o
   where o.id = _order_id;
  if not found then
    return jsonb_build_object('permitido', false, 'motivo', 'pedido_nao_encontrado');
  end if;

  if _o.status <> 'paid' then
    return jsonb_build_object('permitido', false, 'motivo', 'pedido_nao_esta_pago');
  end if;

  -- Só o que a FestPag recebeu: venda manual, cortesia e maquininha da portaria
  -- foram pagas direto ao produtor (mesma fronteira da base de repasse).
  if coalesce(_o.sale_origin, 'online') <> 'online' then
    return jsonb_build_object('permitido', false, 'motivo', 'compra_fora_do_site');
  end if;

  _forma := case
    when lower(coalesce(_o.payment_method, '')) like 'pix%'  then 'pix'
    when lower(coalesce(_o.payment_method, '')) like 'card%' then 'cartao'
  end;
  if _forma is null then
    return jsonb_build_object('permitido', false, 'motivo', 'forma_de_pagamento_nao_suportada');
  end if;

  if coalesce(_o.total_amount, 0) <= 0 then
    return jsonb_build_object('permitido', false, 'motivo', 'sem_valor_pago');
  end if;

  -- Pedido com produto da loja (camiseta, combo) fica fora desta primeira
  -- versão: o produto tem retirada e estoque próprios. Vai pelo suporte.
  if exists (select 1 from public.order_product_items i where i.order_id = _order_id) then
    return jsonb_build_object('permitido', false, 'motivo', 'pedido_com_produto');
  end if;

  select e.date, e.time into _e from public.events e where e.id = _o.event_id;
  if not found or _e.date is null then
    return jsonb_build_object('permitido', false, 'motivo', 'evento_nao_encontrado');
  end if;

  -- Data e hora do evento são de Brasília (a coluna é `date` + `time`, sem fuso).
  _inicio := (_e.date + coalesce(_e.time, time '00:00')) at time zone 'America/Sao_Paulo';
  _limite := _inicio - interval '48 hours';

  -- 7 dias corridos em dias de calendário de Brasília, até o fim do 7º dia. O
  -- pedido nasce minutos antes da confirmação do pagamento; contar por dia
  -- inteiro nunca tira prazo do comprador.
  _fim_arrependimento :=
    (((_o.created_at at time zone 'America/Sao_Paulo')::date + 8)::timestamp) at time zone 'America/Sao_Paulo';

  if _agora < _fim_arrependimento and (_inicio - _agora) > interval '7 days' then
    _janela := 'arrependimento';
  elsif _agora <= _limite then
    _janela := 'ate_48h';
  else
    return jsonb_build_object(
      'permitido', false, 'motivo', 'fora_do_prazo',
      'forma', _forma, 'inicio_evento', _inicio, 'limite', _limite);
  end if;

  -- A regra que vale é a do dia da compra: a versão da Política que o
  -- comprador aceitou no pagamento.
  --
  -- ⚠️ O aceite é gravado quando a pessoa escolhe como pagar, ANTES de o pedido
  -- existir: em produção `aceites_legais.pedido_id` está sempre vazio (medido
  -- em 02/10/2026, 90 aceites de checkout, nenhum com pedido). Por isso a
  -- procura é pelo aceite da mesma pessoa mais próximo ANTES da compra. Se um
  -- dia o pedido passar a ser gravado, ele ganha.
  select a.versao into _versao
    from public.aceites_legais a
   where a.documento = 'reembolso'
     and (a.pedido_id = _order_id
          or (a.usuario_id = _o.user_id
              and a.aceito_em <= _o.created_at + interval '30 minutes'
              and a.aceito_em >= _o.created_at - interval '24 hours'))
   order by (a.pedido_id = _order_id) desc nulls last, a.aceito_em desc
   limit 1;
  -- Compra sem aceite gravado (anterior a 22/09, ou o registro falhou): vale o
  -- texto que estava no ar naquele dia. O novo entrou em 01/10/2026 às 12h25.
  if _versao is null then
    _versao := case when _o.created_at < timestamptz '2026-10-01 12:25:00-03'
                    then '2026-05-14' else '2026-09-30' end;
  end if;
  _texto_antigo := _versao < '2026-09-30';

  -- [TAXA] Hoje: a taxa só volta para quem aceitou o texto antigo, e só no
  -- arrependimento. Para devolver a taxa nos 7 dias a todos, trocar por:
  --   _devolve_taxa := (_janela = 'arrependimento');
  _devolve_taxa := (_janela = 'arrependimento' and _texto_antigo);

  return jsonb_build_object(
    'permitido', true,
    'janela', _janela,
    'devolve_taxa', _devolve_taxa,
    'versao_aceita', _versao,
    'forma', _forma,
    'inicio_evento', _inicio,
    'limite', _limite);
end;
$regra$;

comment on function public.reembolso_regra(uuid, timestamptz) is
  'A regra de reembolso, em um lugar só: prazo, janela e se a taxa volta. Espelha a Política de Reembolso. Mudou lá, muda aqui.';

-- ── 2b. O valor de cada ingresso ────────────────────────────────────────────
-- O valor do pedido para o produtor, ANTES de qualquer reembolso. É a fórmula
-- que estava em `order_producer_value` até hoje, copiada da produção sem mudar
-- uma vírgula. A função de sempre passa a descontar os reembolsos (seção 6).
create or replace function public.order_producer_value_bruto(o public.orders)
returns numeric
language sql
stable
security definer
set search_path to 'public'
as $function$
  SELECT COALESCE(
    (SELECT SUM(f.unit_face * f.quantity) FROM public.order_line_face f WHERE f.order_id = o.id)
      - COALESCE(o.discount_amount, 0),
    COALESCE(o.total_amount, 0) - COALESCE(o.service_fee_amount, 0)
  );
$function$;

comment on function public.order_producer_value_bruto(public.orders) is
  'Valor dos ingressos de um pedido (sem taxa e sem juro), antes de descontar reembolso. Uso interno: order_producer_value e o rateio do reembolso.';

-- Quanto vale cada ingresso de um pedido: o valor dos ingressos (já com o
-- desconto do cupom) e a taxa de serviço, repartidos pelo preço de face de
-- cada um. Conta em centavos e distribui a sobra, para a soma de todos os
-- ingressos bater EXATAMENTE com o pedido: devolver os 3 ingressos de um
-- pedido de R$ 100,00 dá R$ 100,00, nunca R$ 99,99.
create or replace function public.reembolso_valores(_order_id uuid)
returns table (ticket_id uuid, valor_ingresso numeric, valor_taxa numeric)
language sql
stable
security definer
set search_path = public
as $valores$
  with pedido as (
    select o.id,
           round(greatest(0, public.order_producer_value_bruto(o)) * 100)::bigint as ingressos_cent,
           -- A taxa que o COMPRADOR pagou. Quando o produtor absorve a taxa, o
           -- comprador não pagou nada além do ingresso e não há taxa a discutir.
           round(greatest(0, least(coalesce(o.service_fee_amount, 0),
                                   coalesce(o.total_amount, 0) - public.order_producer_value_bruto(o))) * 100)::bigint as taxa_cent
      from public.orders o
     where o.id = _order_id
  ),
  t as (
    select tk.id,
           coalesce(
             (select max(f.unit_face) from public.order_line_face f
               where f.order_id = tk.order_id and f.lot_id = tk.lot_id),
             l.price,
             0)::numeric as peso
      from public.tickets tk
      left join public.event_lots l on l.id = tk.lot_id
     where tk.order_id = _order_id
       and tk.status <> 'pending'
  ),
  s as (select coalesce(sum(peso), 0) as soma, count(*) as n from t),
  p as (
    -- Sem preço de face conhecido (mesa, pedido antigo): reparte por igual.
    select t.id,
           case when s.soma > 0 then t.peso / s.soma else 1.0 / nullif(s.n, 0) end as w
      from t, s
  ),
  c as (
    select p.id,
           floor(pedido.ingressos_cent * p.w)                                as ing_base,
           pedido.ingressos_cent * p.w - floor(pedido.ingressos_cent * p.w)  as ing_resto,
           floor(pedido.taxa_cent * p.w)                                     as taxa_base,
           pedido.taxa_cent * p.w - floor(pedido.taxa_cent * p.w)            as taxa_resto,
           pedido.ingressos_cent, pedido.taxa_cent
      from p, pedido
  ),
  d as (
    select c.*,
           row_number() over (order by c.ing_resto desc, c.id)  as ing_ordem,
           row_number() over (order by c.taxa_resto desc, c.id) as taxa_ordem,
           c.ingressos_cent - sum(c.ing_base) over ()           as ing_sobra,
           c.taxa_cent - sum(c.taxa_base) over ()               as taxa_sobra
      from c
  )
  select d.id,
         ((d.ing_base  + case when d.ing_ordem  <= d.ing_sobra  then 1 else 0 end) / 100.0)::numeric(12,2),
         ((d.taxa_base + case when d.taxa_ordem <= d.taxa_sobra then 1 else 0 end) / 100.0)::numeric(12,2)
    from d;
$valores$;

comment on function public.reembolso_valores(uuid) is
  'Valor de cada ingresso de um pedido (ingresso e taxa), em rateio que fecha no centavo. Fonte única do valor a devolver.';

-- ── 3. As portas do comprador ───────────────────────────────────────────────
-- Por que um ingresso não pode entrar no pedido. Nulo = pode.
create or replace function public.reembolso_motivo_do_ingresso(_ticket_id uuid, _dono uuid)
returns text
language sql
stable
security definer
set search_path = public
as $motivo$
  select case
    when t.status = 'used' or t.validated_at is not null then 'ingresso_ja_utilizado'
    when t.status = 'cancelled' then 'ingresso_ja_cancelado'
    when t.status <> 'valid' then 'ingresso_indisponivel'
    when t.user_id is distinct from _dono then 'ingresso_transferido'
    when t.abada_redeemed_at is not null then 'abada_ja_retirado'
    when exists (select 1 from public.ticket_transfers tr
                  where tr.ticket_id = t.id and tr.status = 'pendente' and tr.expires_at > now())
      then 'transferencia_em_andamento'
    when exists (select 1 from public.reembolso_ingressos ri
                   join public.reembolsos r on r.id = ri.reembolso_id
                  where ri.ticket_id = t.id and r.status = 'solicitado')
      then 'reembolso_em_analise'
  end
  from public.tickets t
  where t.id = _ticket_id;
$motivo$;

-- O que a tela mostra ANTES de o comprador confirmar: se pode, por que não
-- pode, quais ingressos entram e quanto volta. Não grava nada.
create or replace function public.reembolso_simular(_order_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $sim$
declare
  _uid   uuid := auth.uid();
  _dono  uuid;
  _regra jsonb;
  _mesa  boolean;
  _ingressos jsonb;
  _aberto jsonb;
begin
  if _uid is null then
    return jsonb_build_object('permitido', false, 'motivo', 'nao_autenticado');
  end if;

  select o.user_id into _dono from public.orders o where o.id = _order_id;
  if not found or _dono is distinct from _uid then
    return jsonb_build_object('permitido', false, 'motivo', 'pedido_nao_e_seu');
  end if;

  _regra := public.reembolso_regra(_order_id);

  select exists (select 1 from public.tickets t where t.order_id = _order_id and t.event_seat_id is not null)
    into _mesa;

  select coalesce(jsonb_agg(jsonb_build_object(
           'ticket_id', t.id,
           'codigo', upper(left(t.ticket_code, 8)),
           'titular', t.holder_name,
           'nome', coalesce(l.name, s.label, 'Ingresso'),
           'motivo', public.reembolso_motivo_do_ingresso(t.id, _dono),
           'valor_ingresso', v.valor_ingresso,
           'valor_taxa', v.valor_taxa
         ) order by coalesce(s.label, t.ticket_code)), '[]'::jsonb)
    into _ingressos
    from public.tickets t
    join public.reembolso_valores(_order_id) v on v.ticket_id = t.id
    left join public.event_lots l on l.id = t.lot_id
    left join public.event_seats s on s.id = t.event_seat_id
   where t.order_id = _order_id;

  select jsonb_build_object('id', r.id, 'numero', r.numero, 'solicitado_em', r.solicitado_em)
    into _aberto
    from public.reembolsos r
   where r.order_id = _order_id and r.status = 'solicitado'
   limit 1;

  -- Mesa é vendida inteira e volta inteira. Com algum lugar já usado, não há
  -- como devolver a mesa.
  if (_regra->>'permitido')::boolean and _mesa and exists (
       select 1 from public.tickets t
        where t.order_id = _order_id and t.status <> 'pending'
          and public.reembolso_motivo_do_ingresso(t.id, _dono) is not null) then
    _regra := jsonb_build_object('permitido', false, 'motivo',
                case when _aberto is not null then 'reembolso_em_analise' else 'mesa_indisponivel' end)
              || jsonb_build_object('forma', _regra->'forma', 'limite', _regra->'limite');
  end if;

  return _regra || jsonb_build_object(
    'mesa', _mesa,
    'ingressos', _ingressos,
    'pedido_aberto', _aberto);
end;
$sim$;

comment on function public.reembolso_simular(uuid) is
  'O que a tela de Meus Ingressos mostra antes do pedido: se pode, o motivo quando não pode, os ingressos e os valores. Não grava nada.';

-- O pedido. Devolve {ok:false, error:<código>} em vez de estourar: a tela
-- traduz o código para uma frase, e nenhum erro de regra vira "erro interno".
create or replace function public.reembolso_solicitar(
  _order_id       uuid,
  _ticket_ids     uuid[],
  _chave_pix      text default null,
  _tipo_chave_pix text default null,
  _motivo         text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $sol$
declare
  _uid    uuid := auth.uid();
  _o      record;
  _regra  jsonb;
  _ids    uuid[];
  _n      int;
  _mesa   boolean;
  _forma  text;
  _chave  text;
  _tipo   text;
  _motivo_limpo text;
  _devolve_taxa boolean;
  _v_ing  numeric(12,2);
  _v_taxa numeric(12,2);
  _total  numeric(12,2);
  _id     uuid;
  _numero bigint;
begin
  if _uid is null then
    return jsonb_build_object('ok', false, 'error', 'nao_autenticado');
  end if;

  -- A trava do pedido põe em fila dois cliques simultâneos na mesma compra.
  select o.id, o.user_id, o.event_id into _o
    from public.orders o
   where o.id = _order_id
   for update;
  if not found or _o.user_id is distinct from _uid then
    return jsonb_build_object('ok', false, 'error', 'pedido_nao_e_seu');
  end if;

  _regra := public.reembolso_regra(_order_id);
  if not (_regra->>'permitido')::boolean then
    return jsonb_build_object('ok', false, 'error', _regra->>'motivo', 'limite', _regra->'limite');
  end if;
  _forma := _regra->>'forma';
  _devolve_taxa := (_regra->>'devolve_taxa')::boolean;

  select array_agg(distinct x) into _ids from unnest(coalesce(_ticket_ids, '{}'::uuid[])) as x where x is not null;
  if _ids is null or array_length(_ids, 1) is null then
    return jsonb_build_object('ok', false, 'error', 'nenhum_ingresso_escolhido');
  end if;

  if exists (select 1 from public.reembolsos r where r.order_id = _order_id and r.status = 'solicitado') then
    return jsonb_build_object('ok', false, 'error', 'reembolso_em_analise');
  end if;

  -- Pedir e desistir em sequência dispara aviso para a casa a cada vez.
  if (select count(*) from public.reembolsos r where r.order_id = _order_id) >= 5 then
    return jsonb_build_object('ok', false, 'error', 'limite_de_pedidos');
  end if;

  -- Trava os ingressos escolhidos: nenhum check-in passa no meio deste pedido.
  select count(*) into _n
    from (select t.id from public.tickets t
           where t.id = any(_ids) and t.order_id = _order_id
           for update) travados;
  if _n <> array_length(_ids, 1) then
    return jsonb_build_object('ok', false, 'error', 'ingresso_invalido');
  end if;

  if exists (select 1 from unnest(_ids) as x
              where public.reembolso_motivo_do_ingresso(x, _uid) is not null) then
    return jsonb_build_object('ok', false, 'error', 'ingresso_indisponivel',
      'detalhe', (select jsonb_agg(jsonb_build_object('ticket_id', x, 'motivo', public.reembolso_motivo_do_ingresso(x, _uid)))
                    from unnest(_ids) as x
                   where public.reembolso_motivo_do_ingresso(x, _uid) is not null));
  end if;

  -- Mesa volta inteira: todos os lugares do pedido, juntos.
  select exists (select 1 from public.tickets t where t.order_id = _order_id and t.event_seat_id is not null)
    into _mesa;
  if _mesa and exists (select 1 from public.tickets t
                        where t.order_id = _order_id and t.status <> 'pending' and not (t.id = any(_ids))) then
    return jsonb_build_object('ok', false, 'error', 'mesa_inteira');
  end if;

  if _forma = 'pix' then
    _chave := nullif(btrim(coalesce(_chave_pix, '')), '');
    _tipo  := nullif(lower(btrim(coalesce(_tipo_chave_pix, ''))), '');
    if _chave is null or length(_chave) < 5 or length(_chave) > 140 then
      return jsonb_build_object('ok', false, 'error', 'chave_pix_invalida');
    end if;
    if _tipo is null or _tipo not in ('cpf','cnpj','email','telefone','aleatoria') then
      return jsonb_build_object('ok', false, 'error', 'tipo_de_chave_invalido');
    end if;
  end if;

  _motivo_limpo := nullif(left(btrim(coalesce(_motivo, '')), 500), '');

  select coalesce(sum(v.valor_ingresso), 0), coalesce(sum(v.valor_taxa), 0)
    into _v_ing, _v_taxa
    from public.reembolso_valores(_order_id) v
   where v.ticket_id = any(_ids);

  _total := _v_ing + case when _devolve_taxa then _v_taxa else 0 end;
  if _total <= 0 then
    return jsonb_build_object('ok', false, 'error', 'sem_valor_pago');
  end if;

  insert into public.reembolsos
    (order_id, event_id, user_id, valor_ingressos, valor_taxa, devolve_taxa, valor_a_devolver,
     regra, forma, chave_pix, tipo_chave_pix, motivo)
  values
    (_order_id, _o.event_id, _uid, _v_ing, _v_taxa, _devolve_taxa, _total,
     _regra, _forma, _chave, _tipo, _motivo_limpo)
  returning id, numero into _id, _numero;

  insert into public.reembolso_ingressos (reembolso_id, ticket_id, valor_ingresso, valor_taxa)
  select _id, v.ticket_id, v.valor_ingresso, v.valor_taxa
    from public.reembolso_valores(_order_id) v
   where v.ticket_id = any(_ids);

  insert into public.audit_logs (actor_id, action, target_type, target_id, metadata)
  values (_uid, 'refund_requested', 'order', _order_id,
          jsonb_build_object('reembolso_id', _id, 'numero', _numero, 'ingressos', array_length(_ids, 1),
                             'valor_a_devolver', _total, 'janela', _regra->>'janela', 'forma', _forma));

  return jsonb_build_object(
    'ok', true, 'reembolso_id', _id, 'numero', _numero,
    'valor_a_devolver', _total, 'valor_ingressos', _v_ing, 'valor_taxa', _v_taxa,
    'devolve_taxa', _devolve_taxa, 'forma', _forma);
end;
$sol$;

comment on function public.reembolso_solicitar(uuid, uuid[], text, text, text) is
  'O comprador pede o reembolso dos ingressos escolhidos. Só cria o pedido e bloqueia os ingressos: quem cancela é a casa, na aprovação.';

-- Voltar atrás, enquanto a casa não respondeu. Libera os ingressos na hora.
create or replace function public.reembolso_desistir(_reembolso_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $des$
declare
  _uid uuid := auth.uid();
  _r   record;
begin
  if _uid is null then
    return jsonb_build_object('ok', false, 'error', 'nao_autenticado');
  end if;

  select r.id, r.user_id, r.status, r.order_id, r.numero into _r
    from public.reembolsos r
   where r.id = _reembolso_id
   for update;
  if not found or _r.user_id is distinct from _uid then
    return jsonb_build_object('ok', false, 'error', 'reembolso_nao_e_seu');
  end if;
  if _r.status <> 'solicitado' then
    return jsonb_build_object('ok', false, 'error', 'reembolso_ja_respondido', 'status', _r.status);
  end if;

  update public.reembolsos
     set status = 'desistido', desistido_em = now()
   where id = _reembolso_id;

  insert into public.audit_logs (actor_id, action, target_type, target_id, metadata)
  values (_uid, 'refund_request_withdrawn', 'order', _r.order_id,
          jsonb_build_object('reembolso_id', _r.id, 'numero', _r.numero));

  return jsonb_build_object('ok', true);
end;
$des$;

comment on function public.reembolso_desistir(uuid) is
  'O comprador desiste do pedido de reembolso antes da resposta da casa. Os ingressos voltam a valer.';

-- ── 4. A trava ──────────────────────────────────────────────────────────────
-- Ingresso com reembolso EM ANÁLISE não entra no evento, não troca de dono e
-- não retira abadá. Mora no banco, e não em cada porta, porque são várias
-- (portaria, facial, totem do parceiro, painel do produtor) e uma esquecida
-- bastaria para a pessoa entrar E receber o dinheiro de volta.
--
-- Cancelar o ingresso (valid → cancelled) continua livre: é o que a aprovação
-- e o cancelamento pelo produtor fazem.
create or replace function public.barrar_ingresso_em_reembolso()
returns trigger
language plpgsql
security definer
set search_path = public
as $trava$
begin
  if exists (select 1
               from public.reembolso_ingressos ri
               join public.reembolsos r on r.id = ri.reembolso_id
              where ri.ticket_id = old.id and r.status = 'solicitado') then
    raise exception 'ingresso_em_reembolso'
      using errcode = 'P0001',
            hint = 'Este ingresso tem um pedido de reembolso em análise e está bloqueado.';
  end if;
  return new;
end;
$trava$;

drop trigger if exists trg_tickets_barrar_em_reembolso on public.tickets;
create trigger trg_tickets_barrar_em_reembolso
  before update on public.tickets
  for each row
  when (old.status = 'valid' and (
          new.status = 'used'
          or new.user_id is distinct from old.user_id
          or new.abada_redeemed_at is distinct from old.abada_redeemed_at))
  execute function public.barrar_ingresso_em_reembolso();

-- Iniciar transferência não mexe na linha do ingresso, então a trava acima não
-- pega: barra aqui, na criação da transferência.
create or replace function public.barrar_transferencia_em_reembolso()
returns trigger
language plpgsql
security definer
set search_path = public
as $trava$
begin
  if exists (select 1
               from public.reembolso_ingressos ri
               join public.reembolsos r on r.id = ri.reembolso_id
              where ri.ticket_id = new.ticket_id and r.status = 'solicitado') then
    raise exception 'ingresso_em_reembolso'
      using errcode = 'P0001',
            hint = 'Este ingresso tem um pedido de reembolso em análise e está bloqueado.';
  end if;
  return new;
end;
$trava$;

drop trigger if exists trg_transferencia_barrar_em_reembolso on public.ticket_transfers;
create trigger trg_transferencia_barrar_em_reembolso
  before insert on public.ticket_transfers
  for each row execute function public.barrar_transferencia_em_reembolso();

-- ── 5. As portas da casa ────────────────────────────────────────────────────
-- A fila. Traz tudo o que quem paga precisa para decidir e pagar sem ir ao
-- banco: quem, qual evento, quais ingressos, quanto, por onde, e se o produtor
-- já recebeu este dinheiro.
create or replace function public.admin_reembolsos_listar(p_status text default null)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $lista$
declare
  _saida jsonb;
begin
  if not public.has_role(auth.uid(), 'admin'::app_role) then
    raise exception 'not_admin' using errcode = '42501';
  end if;

  select coalesce(jsonb_agg(linha order by ordem_status, solicitado_em), '[]'::jsonb)
    into _saida
    from (
      select
        case r.status when 'solicitado' then 1 when 'aprovado' then 2 else 3 end as ordem_status,
        r.solicitado_em,
        jsonb_build_object(
          'id', r.id,
          'numero', r.numero,
          'status', r.status,
          'order_id', r.order_id,
          'event_id', r.event_id,
          'comprador', o.customer_name,
          'comprador_cpf', o.customer_cpf,
          'comprador_email', o.customer_email,
          'comprador_telefone', o.customer_phone,
          'evento', e.title,
          'data_do_evento', e.date,
          'hora_do_evento', e.time,
          'forma', r.forma,
          'chave_pix', r.chave_pix,
          'tipo_chave_pix', r.tipo_chave_pix,
          'payment_method', o.payment_method,
          'provider_transaction_id', o.provider_transaction_id,
          'mp_payment_id', o.mp_payment_id,
          'total_pago', o.total_amount,
          'comprado_em', o.created_at,
          'valor_ingressos', r.valor_ingressos,
          'valor_taxa', r.valor_taxa,
          'devolve_taxa', r.devolve_taxa,
          'valor_a_devolver', r.valor_a_devolver,
          'regra', r.regra,
          'motivo', r.motivo,
          'solicitado_em', r.solicitado_em,
          'decidido_em', r.decidido_em,
          'motivo_recusa', r.motivo_recusa,
          'modo_cancelamento', r.modo_cancelamento,
          'pago_em', r.pago_em,
          'observacao_pagamento', r.observacao_pagamento,
          'comprovante_path', r.comprovante_path,
          'ingressos', (
            select coalesce(jsonb_agg(jsonb_build_object(
                     'ticket_id', t.id,
                     'codigo', upper(left(t.ticket_code, 8)),
                     'titular', t.holder_name,
                     'nome', coalesce(l.name, s.label, 'Ingresso'),
                     'status', t.status,
                     'valor_ingresso', ri.valor_ingresso,
                     'valor_taxa', ri.valor_taxa) order by t.ticket_code), '[]'::jsonb)
              from public.reembolso_ingressos ri
              join public.tickets t on t.id = ri.ticket_id
              left join public.event_lots l on l.id = t.lot_id
              left join public.event_seats s on s.id = t.event_seat_id
             where ri.reembolso_id = r.id),
          'ingressos_do_pedido', (select count(*) from public.tickets t where t.order_id = r.order_id and t.status <> 'pending'),
          -- O que sobra para o produtor neste evento, já descontados os
          -- reembolsos, os repasses pagos e os pedidos de repasse abertos.
          -- Negativo = o produtor já recebeu este dinheiro e a casa vai devolver
          -- do próprio bolso.
          'saldo_do_produtor', public.base_de_repasse(r.event_id)
              - (select coalesce(sum(p.net_amount), 0) from public.payouts p
                  where p.event_id = r.event_id and p.status in ('paid', 'requested'))
        ) as linha
      from public.reembolsos r
      join public.orders o on o.id = r.order_id
      left join public.events e on e.id = r.event_id
     where p_status is null or r.status = p_status
    ) q;

  return _saida;
end;
$lista$;

comment on function public.admin_reembolsos_listar(text) is
  'A fila de reembolsos para a casa (só admin). Traz comprador, evento, ingressos, valores, forma de devolução e o saldo do produtor.';

-- Aprovar: é AQUI que o ingresso é cancelado e a vaga volta para a venda.
-- Não movimenta dinheiro: o pedido passa a esperar o pagamento, feito por fora.
create or replace function public.admin_reembolso_aprovar(p_reembolso_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $apr$
declare
  _uid   uuid := auth.uid();
  _r     record;
  _o     record;
  _sobram int;
  _tem_produto boolean;
  _lot   record;
  _modo  text;
  _cancelados int := 0;
begin
  if not public.has_role(_uid, 'admin'::app_role) then
    raise exception 'not_admin' using errcode = '42501';
  end if;

  select r.id, r.status, r.order_id, r.numero into _r
    from public.reembolsos r
   where r.id = p_reembolso_id
   for update;
  if not found then
    return jsonb_build_object('ok', false, 'error', 'reembolso_nao_encontrado');
  end if;
  if _r.status <> 'solicitado' then
    return jsonb_build_object('ok', false, 'error', 'invalid_status', 'current_status', _r.status);
  end if;

  select o.id, o.status into _o from public.orders o where o.id = _r.order_id for update;

  -- Marca o pedido de reembolso PRIMEIRO: a trava dos ingressos olha o status
  -- 'solicitado', e o cancelamento logo abaixo não pode esbarrar nela.
  update public.reembolsos
     set status = 'aprovado', decidido_em = now(), decidido_por = _uid
   where id = p_reembolso_id;

  if _o.status = 'paid' then
    -- Ingressos do pedido que ficam de pé depois deste reembolso.
    select count(*) into _sobram
      from public.tickets t
     where t.order_id = _r.order_id
       and t.status in ('valid', 'used')
       and not exists (select 1 from public.reembolso_ingressos ri
                        where ri.reembolso_id = p_reembolso_id and ri.ticket_id = t.id);
    select exists (select 1 from public.order_product_items i where i.order_id = _r.order_id)
      into _tem_produto;

    if _sobram = 0 and not _tem_produto then
      -- O pedido inteiro foi devolvido: a porta de sempre faz a cascata
      -- (estoque, mesa, ingressos, cupom, auditoria) e o pedido vira 'refunded'.
      perform public.cancel_paid_order(_r.order_id, 'refunded',
                'Reembolso nº ' || _r.numero || ' aprovado pela casa');
      _modo := 'pedido_inteiro';
    else
      -- Sobrou ingresso: o pedido continua pago; só os devolvidos são cancelados.
      if exists (select 1 from public.reembolso_ingressos ri
                   join public.tickets t on t.id = ri.ticket_id
                  where ri.reembolso_id = p_reembolso_id and t.event_seat_id is not null) then
        raise exception 'mesa_parcial_nao_suportada' using errcode = '22023';
      end if;

      -- Marca os ingressos primeiro, devolve o estoque depois (padrão da casa:
      -- inverter reabre venda em dobro sob carga).
      for _lot in
        with cancelados as (
          update public.tickets t
             set status = 'cancelled'
           where t.status = 'valid'
             and t.id in (select ri.ticket_id from public.reembolso_ingressos ri
                           where ri.reembolso_id = p_reembolso_id)
          returning t.lot_id
        )
        select lot_id, count(*)::int as qty from cancelados group by lot_id
      loop
        _cancelados := _cancelados + _lot.qty;
        if _lot.lot_id is not null then
          update public.event_lots
             set sold_quantity = greatest(0, sold_quantity - _lot.qty)
           where id = _lot.lot_id;
        end if;
      end loop;

      insert into public.audit_logs (actor_id, action, target_type, target_id, metadata)
      values ('95628c4a-8040-44ed-83c5-d6a5b8793926', 'paid_order_partially_refunded', 'order', _r.order_id,
              jsonb_build_object('reembolso_id', p_reembolso_id, 'numero', _r.numero, 'ingressos_cancelados', _cancelados));
      _modo := 'parcial';
    end if;
  else
    -- O pedido já saiu de 'paid' por outro caminho (produtor cancelou,
    -- contestação). Não há o que cancelar; sobra só o pagamento a conferir.
    _modo := 'pedido_ja_encerrado';
  end if;

  update public.reembolsos set modo_cancelamento = _modo where id = p_reembolso_id;

  insert into public.audit_logs (actor_id, action, target_type, target_id, metadata)
  values (_uid, 'refund_approved', 'order', _r.order_id,
          jsonb_build_object('reembolso_id', p_reembolso_id, 'numero', _r.numero, 'modo', _modo));

  return jsonb_build_object('ok', true, 'status', 'aprovado', 'modo', _modo);
end;
$apr$;

comment on function public.admin_reembolso_aprovar(uuid) is
  'A casa aprova o reembolso: cancela os ingressos e devolve a vaga. Não movimenta dinheiro.';

create or replace function public.admin_reembolso_recusar(p_reembolso_id uuid, p_motivo text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $rec$
declare
  _uid uuid := auth.uid();
  _r   record;
  _motivo text := nullif(left(btrim(coalesce(p_motivo, '')), 500), '');
begin
  if not public.has_role(_uid, 'admin'::app_role) then
    raise exception 'not_admin' using errcode = '42501';
  end if;
  -- O comprador lê este motivo em Meus Ingressos: recusa sem explicação não vale.
  if _motivo is null then
    return jsonb_build_object('ok', false, 'error', 'motivo_obrigatorio');
  end if;

  select r.id, r.status, r.order_id, r.numero into _r
    from public.reembolsos r where r.id = p_reembolso_id for update;
  if not found then
    return jsonb_build_object('ok', false, 'error', 'reembolso_nao_encontrado');
  end if;
  if _r.status <> 'solicitado' then
    return jsonb_build_object('ok', false, 'error', 'invalid_status', 'current_status', _r.status);
  end if;

  update public.reembolsos
     set status = 'recusado', decidido_em = now(), decidido_por = _uid, motivo_recusa = _motivo
   where id = p_reembolso_id;

  insert into public.audit_logs (actor_id, action, target_type, target_id, metadata)
  values (_uid, 'refund_refused', 'order', _r.order_id,
          jsonb_build_object('reembolso_id', p_reembolso_id, 'numero', _r.numero, 'motivo', _motivo));

  return jsonb_build_object('ok', true, 'status', 'recusado');
end;
$rec$;

comment on function public.admin_reembolso_recusar(uuid, text) is
  'A casa recusa o reembolso, com motivo. Os ingressos voltam a valer.';

-- A baixa: o dinheiro já saiu por fora (PIX ou estorno no cartão).
create or replace function public.admin_reembolso_marcar_pago(p_reembolso_id uuid, p_observacao text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $pago$
declare
  _uid uuid := auth.uid();
  _r   record;
begin
  if not public.has_role(_uid, 'admin'::app_role) then
    raise exception 'not_admin' using errcode = '42501';
  end if;

  select r.id, r.status, r.order_id, r.numero, r.valor_a_devolver into _r
    from public.reembolsos r where r.id = p_reembolso_id for update;
  if not found then
    return jsonb_build_object('ok', false, 'error', 'reembolso_nao_encontrado');
  end if;
  if _r.status <> 'aprovado' then
    return jsonb_build_object('ok', false, 'error', 'invalid_status', 'current_status', _r.status);
  end if;

  update public.reembolsos
     set status = 'pago', pago_em = now(), pago_por = _uid,
         observacao_pagamento = nullif(left(btrim(coalesce(p_observacao, '')), 500), '')
   where id = p_reembolso_id;

  insert into public.audit_logs (actor_id, action, target_type, target_id, metadata)
  values (_uid, 'refund_paid', 'order', _r.order_id,
          jsonb_build_object('reembolso_id', p_reembolso_id, 'numero', _r.numero, 'valor', _r.valor_a_devolver));

  return jsonb_build_object('ok', true, 'status', 'pago', 'pago_em', now());
end;
$pago$;

comment on function public.admin_reembolso_marcar_pago(uuid, text) is
  'A casa dá baixa no reembolso depois de pagar por fora. Só registra: o sistema não movimenta dinheiro.';

create or replace function public.admin_reembolso_anexar_comprovante(p_reembolso_id uuid, p_path text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $anexo$
begin
  if not public.has_role(auth.uid(), 'admin'::app_role) then
    raise exception 'not_admin' using errcode = '42501';
  end if;
  if nullif(btrim(coalesce(p_path, '')), '') is null then
    return jsonb_build_object('ok', false, 'error', 'caminho_obrigatorio');
  end if;

  update public.reembolsos
     set comprovante_path = btrim(p_path)
   where id = p_reembolso_id and status in ('aprovado', 'pago');
  if not found then
    return jsonb_build_object('ok', false, 'error', 'reembolso_nao_encontrado');
  end if;
  return jsonb_build_object('ok', true);
end;
$anexo$;

-- A conferência do "oi": o que está parado esperando a casa (analisar ou pagar).
-- É a rede que funciona mesmo com WhatsApp e push fora do ar.
create or replace function public.reembolsos_esperando()
returns table (
  reembolso_id   uuid,
  numero         bigint,
  situacao       text,
  comprador      text,
  evento         text,
  valor          numeric,
  forma          text,
  pedido_em      timestamptz,
  data_do_evento date,
  avisado_em     timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $q$
begin
  if not public.has_role(auth.uid(), 'admin'::app_role) then
    raise exception 'not_admin' using errcode = '42501';
  end if;

  return query
  select r.id, r.numero,
         case r.status when 'solicitado' then 'esperando análise' else 'aprovado, esperando pagamento' end,
         o.customer_name, e.title, r.valor_a_devolver, r.forma, r.solicitado_em, e.date,
         (select max(a.enviado_em) from public.reembolso_avisos a where a.reembolso_id = r.id)
    from public.reembolsos r
    join public.orders o on o.id = r.order_id
    left join public.events e on e.id = r.event_id
   where r.status in ('solicitado', 'aprovado')
   order by r.solicitado_em;
end;
$q$;

comment on function public.reembolsos_esperando() is
  'Pedidos de reembolso parados esperando a casa: analisar ou pagar (só admin). Usada na conferência do "oi".';

-- ── 6. A conta do repasse ───────────────────────────────────────────────────
-- Reembolso pedido, aprovado ou pago SAI do valor do produtor. Pedido ainda em
-- análise também sai: é o caso da Luana (01/10), que pediu repasse de um
-- dinheiro que estava voltando para a compradora. Recusado ou desistido, o
-- valor volta sozinho.
--
-- A mudança mora na fórmula única (`order_producer_value`), então o painel do
-- produtor, o pedido de repasse e o aviso de repasse passam a concordar sem
-- que nenhum deles precise saber de reembolso.
--
-- CREATE OR REPLACE, nunca DROP+CREATE (devolveria a permissão ao público).
-- Sem reembolso no pedido, o resultado é IDÊNTICO ao de antes.
create or replace function public.order_producer_value(o public.orders)
returns numeric
language sql
stable
security definer
set search_path to 'public'
as $function$
  SELECT public.order_producer_value_bruto(o)
       - COALESCE((SELECT SUM(r.valor_ingressos)
                     FROM public.reembolsos r
                    WHERE r.order_id = o.id
                      AND r.status IN ('solicitado', 'aprovado', 'pago')), 0);
$function$;

comment on function public.order_producer_value(public.orders) is
  'Valor do ingresso de um pedido para o PRODUTOR (sem taxa de conveniência e sem juro de parcela), já descontado o que foi ou está sendo reembolsado. Fórmula única: usada por request_payout (via base_de_repasse) e pelo painel (producer_order_values).';

-- ── 7. O aviso para a casa ──────────────────────────────────────────────────
-- Mesmo motor do aviso de repasse (23/09): gatilho → pg_net → edge → WhatsApp
-- e push da gestão, com registro do que saiu e repesca do que não saiu.
create table if not exists public.reembolso_avisos (
  id           uuid primary key default gen_random_uuid(),
  reembolso_id uuid not null references public.reembolsos(id) on delete cascade,
  canal        text not null check (canal in ('whatsapp', 'gestao')),
  -- número mascarado ou nome do destino. NUNCA o número inteiro (LGPD).
  destino      text,
  -- nulo = ainda não saiu. É este campo que a repesca olha.
  enviado_em   timestamptz,
  tentativas   integer not null default 0,
  ultimo_erro  text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (reembolso_id, canal)
);

comment on table public.reembolso_avisos is
  'Prova de que o aviso de pedido de reembolso saiu. Uma linha por pedido e canal; enviado_em nulo = a repesca ainda vai tentar.';

create index if not exists idx_reembolso_avisos_pendentes
  on public.reembolso_avisos (reembolso_id) where enviado_em is null;

alter table public.reembolso_avisos enable row level security;

drop policy if exists "admin le os avisos de reembolso" on public.reembolso_avisos;
create policy "admin le os avisos de reembolso"
  on public.reembolso_avisos for select
  using (public.has_role(auth.uid(), 'admin'::app_role));

revoke all on public.reembolso_avisos from anon, authenticated;
grant select on public.reembolso_avisos to authenticated;

drop trigger if exists update_reembolso_avisos_updated_at on public.reembolso_avisos;
create trigger update_reembolso_avisos_updated_at
  before update on public.reembolso_avisos
  for each row execute function public.update_updated_at_column();

-- REGRA DE OURO, igual à do repasse: falhar ao avisar NUNCA pode derrubar o
-- pedido de reembolso. O comprador clicou, o pedido tem que nascer.
create or replace function public.avisar_reembolso_solicitado()
returns trigger
language plpgsql
security definer
set search_path = public
as $fn$
declare
  _segredo text;
begin
  if new.status is distinct from 'solicitado' then
    return new;
  end if;

  select decrypted_secret into _segredo
    from vault.decrypted_secrets where name = 'CRON_SECRET' limit 1;

  if _segredo is null then
    raise warning '[AVISO-REEMBOLSO] CRON_SECRET nao encontrado no Vault; aviso do reembolso % nao foi disparado', new.id;
    return new;
  end if;

  perform net.http_post(
    url     := 'https://nsrromaqysgoxqvqagdm.supabase.co/functions/v1/aviso-reembolso',
    headers := jsonb_build_object(
                 'Content-Type', 'application/json',
                 'X-Cron-Secret', _segredo
               ),
    body    := jsonb_build_object('reembolso_id', new.id, 'origem', 'gatilho'),
    timeout_milliseconds := 25000
  );

  return new;
exception when others then
  raise warning '[AVISO-REEMBOLSO] gatilho falhou para o reembolso %: %', new.id, sqlerrm;
  return new;
end;
$fn$;

comment on function public.avisar_reembolso_solicitado() is
  'Chama a edge aviso-reembolso quando nasce um pedido de reembolso. Nunca derruba a operação que o criou.';

drop trigger if exists trg_reembolsos_aviso on public.reembolsos;
create trigger trg_reembolsos_aviso
  after insert on public.reembolsos
  for each row execute function public.avisar_reembolso_solicitado();

-- A repesca: de 10 em 10 minutos, tenta de novo o que não saiu.
do $cron$
begin
  perform cron.unschedule('aviso-reembolso-repescar');
exception when others then
  null; -- não existia ainda
end;
$cron$;

select cron.schedule(
  'aviso-reembolso-repescar',
  '*/10 * * * *',
  $job$
  select net.http_post(
    url     := 'https://nsrromaqysgoxqvqagdm.supabase.co/functions/v1/aviso-reembolso',
    headers := jsonb_build_object(
                 'Content-Type', 'application/json',
                 'X-Cron-Secret', (select decrypted_secret from vault.decrypted_secrets where name = 'CRON_SECRET' limit 1)
               ),
    body    := jsonb_build_object('modo', 'repescar', 'origem', 'cron'),
    timeout_milliseconds := 25000
  );
  $job$
);

-- ── Permissões ──────────────────────────────────────────────────────────────
-- Função nova nasce com execução liberada ao público. Fecha tudo e abre só o
-- que cada um precisa.

-- Internas: só o banco chama (as portas abaixo são SECURITY DEFINER).
revoke all on function public.reembolso_regra(uuid, timestamptz)             from public, anon, authenticated;
revoke all on function public.reembolso_valores(uuid)                        from public, anon, authenticated;
revoke all on function public.reembolso_motivo_do_ingresso(uuid, uuid)       from public, anon, authenticated;
revoke all on function public.order_producer_value_bruto(public.orders)      from public, anon, authenticated;
revoke all on function public.barrar_ingresso_em_reembolso()                 from public, anon, authenticated;
revoke all on function public.barrar_transferencia_em_reembolso()            from public, anon, authenticated;
revoke all on function public.avisar_reembolso_solicitado()                  from public, anon, authenticated;
grant execute on function public.reembolso_regra(uuid, timestamptz)          to service_role;
grant execute on function public.reembolso_valores(uuid)                     to service_role;
grant execute on function public.reembolso_motivo_do_ingresso(uuid, uuid)    to service_role;
grant execute on function public.order_producer_value_bruto(public.orders)   to service_role;

-- Comprador logado (cada função confere se o pedido é dele).
revoke all on function public.reembolso_simular(uuid)                             from public, anon;
revoke all on function public.reembolso_solicitar(uuid, uuid[], text, text, text) from public, anon;
revoke all on function public.reembolso_desistir(uuid)                            from public, anon;
grant execute on function public.reembolso_simular(uuid)                             to authenticated, service_role;
grant execute on function public.reembolso_solicitar(uuid, uuid[], text, text, text) to authenticated, service_role;
grant execute on function public.reembolso_desistir(uuid)                            to authenticated, service_role;

-- Casa (cada função confere o papel de admin).
revoke all on function public.admin_reembolsos_listar(text)                    from public, anon;
revoke all on function public.admin_reembolso_aprovar(uuid)                    from public, anon;
revoke all on function public.admin_reembolso_recusar(uuid, text)              from public, anon;
revoke all on function public.admin_reembolso_marcar_pago(uuid, text)          from public, anon;
revoke all on function public.admin_reembolso_anexar_comprovante(uuid, text)   from public, anon;
revoke all on function public.reembolsos_esperando()                           from public, anon;
grant execute on function public.admin_reembolsos_listar(text)                  to authenticated, service_role;
grant execute on function public.admin_reembolso_aprovar(uuid)                  to authenticated, service_role;
grant execute on function public.admin_reembolso_recusar(uuid, text)            to authenticated, service_role;
grant execute on function public.admin_reembolso_marcar_pago(uuid, text)        to authenticated, service_role;
grant execute on function public.admin_reembolso_anexar_comprovante(uuid, text) to authenticated, service_role;
grant execute on function public.reembolsos_esperando()                         to authenticated, service_role;
