-- ============================================================================
-- A VIRADA — Bloco 5 (plano de 09/09/2026). Ordem do Gabriel em 09/09 à noite:
-- "não quero um novo tipo de login; quero que seja tudo uma coisa só".
--
-- ⚠️ APLICAR JUNTO COM O PUBLISH deste pacote (mesma manhã), não antes: o site
-- que está no ar hoje ainda escolhe o modal pelo `auth_flow` — virar os eventos
-- antes do publish trocaria a compra sem trocar a página de login. Depois do
-- publish o front ignora a coluna (é sempre o caminho novo); ela fica só como
-- registro.
--
-- O QUE A VIRADA FAZ
--   1. Todo evento passa a usar a conta por CPF com senha + código (`auth_flow = 'v2'`),
--      inclusive os que estão vendendo (Oktoberfest). Quem já tem conta continua
--      entrando com o e-mail + senha de sempre — só ganha o código a mais.
--   2. Evento novo já nasce em `v2`.
--
-- O QUE SAI DO CÓDIGO NO MESMO PACOTE (galho da virada, depois da Porcada validar)
--   · `src/components/auth/AuthModal.tsx` e `SignupWizard.tsx` (o caminho antigo),
--     e o `EventDetails` passa a abrir só o `AuthModalV2`;
--   · na página `/login`, a aba de senha vira "produtor"; cliente entra pelo modal;
--   · edges `send-verification-code`, `verify-email-code`, `send-password-reset-code`,
--     `verify-password-reset-code` e as tabelas `email_verification_codes` e
--     `password_reset_codes` — o motor novo (`auth_codigos`) cobre tudo.
--     ⚠️ O checkout (`CheckoutStepProgressiveForm`) e o aceite de transferência
--     ainda chamam as duas primeiras: trocar antes de apagar.
--
-- COMO VOLTAR ATRÁS (no dia)
--   UPDATE public.events SET auth_flow = 'v1';
--   ALTER TABLE public.events ALTER COLUMN auth_flow SET DEFAULT 'v1';
--   (e republicar o pacote anterior)
-- ============================================================================

ALTER TABLE public.events ALTER COLUMN auth_flow SET DEFAULT 'v2';
UPDATE public.events SET auth_flow = 'v2' WHERE auth_flow <> 'v2';
